### ISSUE TITLE
can u continue this project?

### ISSUE THREAD

**Issue by stickylabdev** [imsenthur/2D_Platformer_AI_Unity#1]
![image](https://user-images.githubusercontent.com/13078369/66491226-93823700-eadc-11e9-9080-6f6bcd25c6df.png)

**Comment by senthurayyappan** [comment]
I'm sorry to inform you that this project has been discontinued, there might be a lot of deprecations now as this project was developed with a much earlier build of Unity.  You can look-up Pathfinding/State-machine assets in the unity store if that is what you're interested in.
